### ISSUE TITLE
Create list of possible component names

### ISSUE THREAD

**Issue by wjk** [Microsoft/vssetup.powershell#10]
I am trying to use this repository as an example of how to locate the MSVC tools (`cl.exe`, `link.exe`, et al) without making any assumptions as to where VS is installed. I understand that I can use the `Select-VSSetupInstance` cmdlet to identify the latest working version of VS that has the required workload. Unfortunately, I do not know what the internal name of the component or workload that contains the MSVC tools is, and therefore do not know what parameters to pass to that cmdlet! Could you please add a listing to this repository of all the workload display names and the corresponding programmatic IDs? This would make use of this code much easier. Thanks!

**Comment by heaths** [comment]
The query API on which the cmdlets are built intentionally does not expose this information. For a list of the supported component names you can select, please see https://www.visualstudio.com/en-us/productinfo/vs2017-install-product--list. Specifically in your case, check out https://www.visualstudio.com/en-us/productinfo/vs2017-install-product-Community.workloads#desktop-development-with-c.
