### ISSUE TITLE
Compatibility with Powershell 6.0?

### ISSUE THREAD

**Issue by mejas** [Microsoft/vssetup.powershell#15]
I tried installing the feature as per the documentation steps and the module seems to install. However, when i attempt to invoke using the following command: `Get-VSSetupInstance`

The command is not detected. Lower versions of PS (5.0 below) seem to work, though.

Specs used:
- PS 6.0.0-alpha.18
- Win7 x64

**Comment by heaths** [comment]
PowerShell 6.0 runs on .NET Core which does not support all the types declared. We are considering how to deal with this, but it is not currently supported.

**Comment by mejas** [comment]
Thank you for the fast response.

**Comment by Manuzor** [comment]
Ran into the same issue. Looking forward to the fix!

**Comment by heaths** [comment]
As of PowerShell Core 6.0 beta 4, the module works. The type `System.Runtime.InteropServices.TypeLibImportClassAttribute` still isn't supported by .NET Standard 2.0, but somehow it still works (perhaps that type is not truly necessary for non-embedded PIAs).
