### ISSUE TITLE
Install command in README doesn't work

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vssetup.powershell#3]
```PS1
Install-Module VSSetup -Scope CurrentUser
```

```
Install-Module : A parameter cannot be found that matches parameter name 'Scope'.
At line:1 char:24
+ Install-Module VSSetup -Scope CurrentUser
+                        ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module
```

Further, I'm very curious how Powershell would know where to resolve VSSetup from.

I am on Windows 10 build 14393.rs1_release.161220-1747

**Comment by heaths** [comment]
PowerShellGet has a list of default repositories including http://powershellgallery.com where this module is published. Run `Get-PSRepository` for a list.

The `Scope` parameter is correct. I use it all the time, and is documented at https://msdn.microsoft.com/en-us/powershell/reference/5.1/powershellget/install-module. Please run `get-module -list PowerShellGet | select * | clip` and paste the output.

**Comment by heaths** [comment]
Also, does `gcm install-module` tell you its from the PowerShellGet module (see "Source" column in default output). If multiple results are returned, the first one listed is what `Install-Module` invokes, which could be wrong. IIRC, the `Scope` parameter has always been supported (I was a beta tester for OneGet/PackageManagement and PowerShellGet, so have been using them for a while).

**Comment by AArnott** [comment]
As discussed offline, I had a stale version of PsGet in my Documents\WindowsPowershell\modules directory. Once I removed it, it worked.
