### ISSUE TITLE
Cannot install VSSetup

### ISSUE THREAD

**Issue by clisc** [Microsoft/vssetup.powershell#31]
Ran the following commands in Admin PowerShell window.  The module did not load properly.  Running Windows internal Microsoft release RS3 RTM Version 10.0.16299 Build 16299.

PS C:\WINDOWS\system32> Install-Module VSSetup -Scope CurrentUser
PS C:\WINDOWS\system32> Get-VSSetupInstance
Get-VSSetupInstance : The term 'Get-VSSetupInstance' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ Get-VSSetupInstance
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-VSSetupInstance:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32> Get-Command -Module VSSetup
PS C:\WINDOWS\system32>

**Comment by clisc** [comment]
Update: Workaround is to download and unzip manually:

PS C:\users\clisc\Downloads> Expand-Archive VSSetup.zip "$([Environment]::GetFolderPath("MyDocuments"))\WindowsPowerShel
l\Modules\VSSetup"
PS C:\users\clisc\Downloads> Import-Module "$([Environment]::GetFolderPath("MyDocuments"))\WindowsPowerShell\Modules\VSS
etup"
PS C:\users\clisc\Downloads> get-command -Module VSSetup

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-VSSetupInstance                                2.0.1.3... VSSetup
Cmdlet          Select-VSSetupInstance                             2.0.1.3... VSSetup


PS C:\users\clisc\Downloads>

**Comment by heaths** [comment]
Make sure `$env:PSModulePath` contains `$([Environment]::GetFolderPath("MyDocuments"))\WindowsPowerShell\Modules`. If you had to import from that path manually, it sounds like it may not be (which it is by default). If not, add it to `$env:PSModulePath`. If it is, this sounds like a bug in PowerShellGet which you can file at https://github.com/PowerShell/PowerShellGet/issues. The package is built correctly to support PSGet.

**Comment by clisc** [comment]
Thanks, that appears to be the issue.  So there are multiple files in the path which need to be there for other software.  If I append the default path below to the end of the path, do you think it will work correctly?

**Comment by heaths** [comment]
I would actually pre-pend the path, but yes. Some software when installed doesn't make sure the default path is still included. PowerShell implemented the environment variable as a replacement, such that the default is not used if anything overwrites the environment variable.

**Comment by clisc** [comment]
Prepending worked.  Thanks!
