### ISSUE TITLE
Support for -ComputerName for remote query of version

### ISSUE THREAD

**Issue by gordonAndersen** [Microsoft/vssetup.powershell#39]
It would be nice if one could do a Get-VSSetupInstance -ComputerName MyBuildserver.
I have tried with something like Invoke-Command MyBuildserver -Scriptblock {Get-VSSetupInstance} without luck.

**Comment by heaths** [comment]
The APIs are not remotable, but you can create a WinRM session to a remote computer and install/execute the module on that remove computer.

```powershell
$session = new-possession RemoteComputerName
invoke-command -session $session { if (!(get-module -list vssetup)) { install-module vssetup -scope currentuser }; get-vssetupinstance -all -pre }
$session | remove-possession
```
