### ISSUE TITLE
The setup configuration provider registration fix

### ISSUE THREAD

**Issue by alexfdezsauco** [Microsoft/vssetup.powershell#48]
I'm looking for a fix of visual studio registration or 'Microsoft Setup Configuration query API' registration (COM?). I know this is not a `vssetup.powershell` issue, but could be fixed by ' `vssetup.powershell`.

I noticed the symptom when I tried to install ReSharper on the VS2017 - 15.7 but the installer showed the following warning message:  

_Installer could not access the Microsoft Setup Configuration query API_

So, I also run `Get-VSSetupInstance` (from this module) and get this error:

_WARNING: The setup configuration provider is not registered. Assuming no registered instances._

**Could be possible add a Cmd-Let to fix the registration?** 

I also run a clean up with:

`%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\resources\app\layout\InstallCleanup.exe -i`

and installed the VS again, but doesn't work.

**Comment by heaths** [comment]
Cleaning up the VS instance was not necessary. Run repair on VS. Often in these cases, the MSI that installs the system-wide configuration API is installed and detected as such, but the registration got removed somehow. Repairing repairs all packages regardless of state.

A faster way is to use my MSI PowerShell module:

```powershell
Install-Module -Scope CurrentUser MSI
Get-MSIRelatedProductInfo '{1571205C-BAD1-4237-BFE6-B77E622C51DB}' | Repair-MSIProduct
```

**Comment by alexfdezsauco** [comment]
Thanks, 

When I run your suggestion I got this error:

`Repair-MSIProduct : An installation package for the product Microsoft Visual Studio Setup Configuration cannot be found. Try the installation again
using a valid copy of the installation package 'Microsoft.VisualStudio.Setup.Configuration.msi'.
At line:1 char:70
+ ... ductInfo '{1571205C-BAD1-4237-BFE6-B77E622C51DB}' | Repair-MSIProduct
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Microsoft Visua...p Configuration:String) [Repair-MSIProduct], PSInstallerException
    + FullyQualifiedErrorId : InstallerError,Microsoft.Tools.WindowsInstaller.PowerShell.Commands.RepairProductCommand

Repair-MSIProduct : Fatal error during installation.
At line:1 char:70
+ ... ductInfo '{1571205C-BAD1-4237-BFE6-B77E622C51DB}' | Repair-MSIProduct
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Repair-MSIProduct], PSInstallerException
    + FullyQualifiedErrorId : InstallerError,Microsoft.Tools.WindowsInstaller.PowerShell.Commands.RepairProductCommand`

this lead me to search into the installed packages and open this file c:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.Setup.Configuration,version=1.16.1163.30317\_package.json and download and install this https://download.visualstudio.microsoft.com/download/pr/12046354/d68d54e233c956ff79799fdf63753c54/Microsoft.VisualStudio.Setup.Configuration.msi

and now is fixed
