### ISSUE TITLE
Script failing when visual studio installed in different location.

### ISSUE THREAD

**Issue by dhmuralikrishna** [microsoft/vssetup.powershell#57]
When visual studio installed in default setup it's working fine. Failing when it's installed in a different location.

**Comment by heaths** [comment]
We have many tests that all use non-default locations. Can you explain a bit more how you're invoking this, what version of Visual Studio you're using, and anything else that might help investigate this?

**Comment by dhmuralikrishna** [comment]
I not an issue. You can close it. Thanks
