### ISSUE TITLE
Failed to install module due to failed access to cloud file

### ISSUE THREAD

**Issue by Tafnu07** [microsoft/vssetup.powershell#61]
When trying to install VSSetup module  by running the following command:

Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser
Install-Module VSSetup -Scope CurrentUser -Force -Confirm:$false

But it fails with "Access to the cloud file is denied"

PackageManagement\Install-Package : Access to the cloud file is denied
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

Not sure how to resolve this issue. Can't seem to find any help online as well.

**Comment by heaths** [comment]
You might check the powershellgallery.com status. This isn't a problem with this PowerShell module, but something with PSGet (PackageManager) or powershellgallery.com itself. See https://aka.ms/psgallery-status/ for status, and https://www.powershellgallery.com/policies/Contact for support options for either the PSGet module or the gallery.

**Comment by MHanafy** [comment]
I've had the same error with Powershell 5; issue got resolved only by installing powershell 7.
