### ISSUE TITLE
need -Require SSIS

### ISSUE THREAD

**Issue by end-user** [Microsoft/vssetup.powershell#72]
I need a way to `-Require SSIS` - that is, get whatever instance supports building Integration Services packages.  Right now, I have a 2019 and a 2022.  My `-Latest` is failing because 2022 does not yet have support for SSIS.  I did a list of the workload/components, but it's not listed.  Is there a way to capture these?
![image](https://user-images.githubusercontent.com/4923193/174880109-beb798d8-7359-4904-9d1c-1a4b2ab34981.png)

**Comment by heaths** [comment]
If you don't see it in https://aka.ms/vs/workloads or by saving a .vsconfig file from that instance that has it and can recognize the workload or component ID, it may be an extension which `-Require` doesn't support.

**Comment by end-user** [comment]
I don't know how [SSIS](https://marketplace.visualstudio.com/items?itemName=SSIS.SqlServerIntegrationServicesProjects) is found.

**Comment by heaths** [comment]
That's an extension, which is not supported by the configuration APIs. If the configuration APIs supported extensions, this would just work in vswhere and vssetup.powershell. Please file a feedback ticket at https://developercommunity.visualstudio.com/search?space=8. There's one or two already about supporting extensions for .vsconfig, for example.
