### ISSUE TITLE
Shared Components and Download Cache Path support

### ISSUE THREAD

**Issue by JohnBeckman** [Microsoft/vssetup.powershell#78]
it would be nice if the tool could report on the Download Cache path and the Shared Components, tools and SDKs path for each of the VS instances.

**Comment by heaths** [comment]
Sorry, but those are implementation details and we don't recommend doing anything directly with them. If you want to minimize the cache, please see https://learn.microsoft.com/visualstudio/install/disable-or-move-the-package-cache.
